# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    tags:
      - cmount
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
dockers:
  - use: buildx
    goarch: amd64
    dockerfile: 'Dockerfile.new'
    build_flag_templates:
    - '--platform=linux/amd64'
    image_templates:
    - 'gaoyb7/rclone:v1_{{ time "20060102" }}-amd64'
  - use: buildx
    goarch: 386
    dockerfile: 'Dockerfile.new'
    build_flag_templates:
    - "--platform=linux/386"
    image_templates:
    - 'gaoyb7/rclone:v1_{{ time "20060102" }}-i386'
  - use: buildx
    goarch: arm64
    dockerfile: 'Dockerfile.new'
    build_flag_templates:
    - '--platform=linux/arm64/v8'
    image_templates:
    - 'gaoyb7/rclone:v1_{{ time "20060102" }}-arm64v8'
  - use: buildx
    goarch: arm
    goarm: 7
    dockerfile: 'Dockerfile.new'
    build_flag_templates:
    - '--platform=linux/arm/v7'
    image_templates:
    - 'gaoyb7/rclone:v1_{{ time "20060102" }}-armv7'
  - use: buildx
    goarch: arm
    goarm: 6
    dockerfile: 'Dockerfile.new'
    build_flag_templates:
    - '--platform=linux/arm/v6'
    image_templates:
    - 'gaoyb7/rclone:v1_{{ time "20060102" }}-armv6'
docker_manifests:
- name_template: 'gaoyb7/rclone:v1_{{ time "20060102" }}'
  image_templates:
  - 'gaoyb7/rclone:v1_{{ time "20060102" }}-amd64'
  - 'gaoyb7/rclone:v1_{{ time "20060102" }}-i386'
  - 'gaoyb7/rclone:v1_{{ time "20060102" }}-arm64v8'
  - 'gaoyb7/rclone:v1_{{ time "20060102" }}-armv7'
  - 'gaoyb7/rclone:v1_{{ time "20060102" }}-armv6'
- name_template: gaoyb7/rclone:latest
  image_templates:
  - 'gaoyb7/rclone:v1_{{ time "20060102" }}-amd64'
  - 'gaoyb7/rclone:v1_{{ time "20060102" }}-i386'
  - 'gaoyb7/rclone:v1_{{ time "20060102" }}-arm64v8'
  - 'gaoyb7/rclone:v1_{{ time "20060102" }}-armv7'
  - 'gaoyb7/rclone:v1_{{ time "20060102" }}-armv6'
snapshot:
  name_template: v1_{{ time "20060102" }}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
